name: Surveillance tickets.cafonline.com

on:
  schedule:
    # Vérifie toutes les 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Run monitoring script
      env:
        IFTTT_WEBHOOK_URL: ${{ secrets.IFTTT_WEBHOOK_URL }}
      run: |
        python monitor.py
    
    - name: Stop workflow if site is accessible
      if: success()
      run: |
        echo "Site accessible détecté - arrêt de la surveillance"
        # Optionnel: désactiver le workflow automatiquement
        # gh workflow disable "Surveillance tickets.cafonline.com"
